[package]
name = "ytm-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
judge-fixtures = []

[dependencies]
async-trait.workspace = true
chrono.workspace = true
futures-util.workspace = true
indexmap.workspace = true
quick-xml.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
flate2.workspace = true
serde_yaml.workspace = true
tokio = { workspace = true, features = ["io-util", "net"] }
