[workspace]
members = ["crates/ytm-core", "crates/ytm-node"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/cpaikr/ytm"
rust-version = "1.92"

[workspace.dependencies]
async-trait = "=0.1.89"
chrono = { version = "=0.4.42", default-features = false, features = ["clock", "serde"] }
futures-util = "=0.3.31"
flate2 = "=1.1.9"
indexmap = { version = "=2.12.1", features = ["serde"] }
napi = { version = "=3.12.1", default-features = false, features = ["async", "napi8"] }
napi-build = "=2.4.1"
napi-derive = "=3.6.3"
quick-xml = "=0.41.0"
reqwest = { version = "=0.13.4", default-features = false, features = ["brotli", "deflate", "gzip", "http2", "rustls", "stream"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = { version = "=1.0.149", features = ["preserve_order"] }
serde_yaml_ng = "=0.10.0"
tokio = { version = "=1.53.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-util = "=0.7.18"

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
panic = "unwind"
