// Generated by scripts/generate-native-packages.mjs from native-targets.json.
const { existsSync } = require("node:fs");
const { join } = require("node:path");

const packageByTarget = {
  "linux-x64-gnu": "@sjunepark/ytm-linux-x64-gnu",
  "linux-arm64-gnu": "@sjunepark/ytm-linux-arm64-gnu",
  "darwin-arm64": "@sjunepark/ytm-darwin-arm64",
  "win32-x64": "@sjunepark/ytm-win32-x64-msvc"
};

const local = join(__dirname, "ytm.node");
if (existsSync(local)) {
  module.exports = require(local);
} else {
  const libc = process.platform === "linux"
    ? (process.report?.getReport()?.header?.glibcVersionRuntime ? "gnu" : "musl")
    : null;
  const key = [process.platform, process.arch, libc].filter(Boolean).join("-");
  const packageName = packageByTarget[key];
  if (!packageName) throw new Error(`@sjunepark/ytm does not support ${key}.`);
  try {
    module.exports = require(packageName);
  } catch (cause) {
    const error = new Error(`The native ytm package for ${key} is not installed correctly.`);
    error.cause = cause;
    throw error;
  }
}
