[package]
name = "ytm-node"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[features]
default = []
judge-fixtures = ["ytm-core/judge-fixtures"]

[dependencies]
futures-util.workspace = true
napi.workspace = true
napi-derive.workspace = true
serde.workspace = true
serde_json.workspace = true
ytm-core = { version = "0.2.0", path = "../ytm-core" }

[build-dependencies]
napi-build.workspace = true
serde.workspace = true
serde_json.workspace = true
