from typing import Awaitable

__version__: str

class NativeClient:
    def __init__(self) -> None: ...
    def run_sync(self, operation: str, input: str, timeout_json: str | None = None) -> str: ...
    def run_async(self, operation: str, input: str, timeout_json: str | None = None) -> Awaitable[str]: ...
    def close_sync(self) -> None: ...
    def close_async(self) -> Awaitable[None]: ...
