from typing import Awaitable

__version__: str

class NativeClient:
    def __init__(self) -> None: ...
    def run_sync(self, operation: str, input: str) -> str: ...
    def run_async(self, operation: str, input: str) -> Awaitable[str]: ...
    def close_sync(self) -> None: ...
    def close_async(self) -> Awaitable[None]: ...
