// Generated by scripts/generate-native-packages.mjs from native-targets.json.
const { existsSync } = require("node:fs");
const { join } = require("node:path");

const packageByTarget = {
  "linux-x64-gnu": "@sjunepark/ytm-linux-x64-gnu",
  "linux-arm64-gnu": "@sjunepark/ytm-linux-arm64-gnu",
  "darwin-arm64": "@sjunepark/ytm-darwin-arm64",
  "win32-x64": "@sjunepark/ytm-win32-x64-msvc"
};

const local = join(__dirname, "ytm.node");
if (existsSync(local)) {
  module.exports = require(local);
} else {
  const libc = process.platform === "linux" ? linuxLibc() : null;
  const key = [process.platform, process.arch, libc].filter(Boolean).join("-");
  const packageName = packageByTarget[key];
  if (!packageName) throw new Error(`@sjunepark/ytm does not support ${key}.`);
  try {
    module.exports = require(packageName);
  } catch (cause) {
    const error = new Error(`The native ytm package for ${key} could not be loaded correctly.`);
    if (missingExpectedPackage(cause, packageName)) {
      error.ytmNativePackageUnavailable = true;
    }
    error.cause = cause;
    throw error;
  }
}

function linuxLibc() {
  try {
    const runtimeVersion = process.report?.getReport()?.header?.glibcVersionRuntime;
    return typeof runtimeVersion === "string" && runtimeVersion.length > 0
      ? "gnu"
      : "unknown-libc";
  } catch {
    return "unknown-libc";
  }
}

function missingExpectedPackage(cause, packageName) {
  if (cause?.code !== "MODULE_NOT_FOUND" || typeof cause.message !== "string") return false;
  const escaped = packageName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^(?:Cannot find module|Cannot find package) ['"]${escaped}['"]`).test(cause.message);
}
